# Site settings
title: Zee Moffatt
description: >- # this means to ignore newlines until "baseurl:"
  Space Systems and Robotics Engineering  
baseurl: ""  # the subpath of your site, e.g. /blog
url: zeemoffatt.com # the base hostname & protocol for your site, e.g. http://example.com
repository: zmoffatt/zmoffatt.github.io


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Zee Moffatt
  image    : Zee_Headshot.jpg
  email    : zdmoffatt@gmail.com
#  github   : username
#  twitter  : username
  linkedin : https://www.linkedin.com/in/zmoffatt/
#  facebook : username


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
#permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
